account/urls.py
from django.urls import path
from django.shortcuts import render
from django.contrib.auth.views import LogoutView
from . import views

app_name = "account"

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("delete-acc/", views.delete_account, name="delete-acc"),
    path(
        "dashboard/",
        lambda request: render(request, "account/dashboard.html"),
        name="dashboard",
    ),
    path("profile/", views.profile, name="profile"),
    path(
        "email-sent/",
        lambda request: render(request, "account/email/email-verification-sent.html"),
        name="email-sent",
    ),
    path("change-password/", views.change_password, name="change-password"),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls"), name="shop"),
    path("email/", include(email_urls)),
    path("account/", include("account.urls")),
    path("cart/", include("cart.urls"), name="cart"),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_view, name="cart"),
    path("add/", views.cart_add, name="add_to_cart"),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_view, name="products"),
    path("product/<slug:slug>/", views.product_detail, name="detail"),
    path("category/<slug:slug>/", views.category_list, name="category"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- CSS -->

    <link
      rel="stylesheet"
      href="https://bootswatch.com/5/flatly/bootstrap.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- JavaScript -->

    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>

    <!-- JavaScript Bundle with Popper -->

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <title>BigCorp</title>

    <style>

      .badge {
        padding-left: 9px;
        padding-right: 9px;
        -webkit-border-radius: 9px;
        -moz-border-radius: 9px;
        border-radius: 9px;
      }
  
      .label-warning[href],
      .badge-warning[href] {
        background-color: #c67605;
      }
      #lblCartCount {
          font-size: 12px;
          background: #3c9700;
          color: #fff;
          padding: 0 5px;
          vertical-align: top;
          margin-left: -2px; 
      }
  


      a {
        font-size: 14px;
        font-weight: 700;
      }
      .superNav {
        font-size: 13px;
      }
      .form-control {
        outline: none !important;
        box-shadow: none !important;
      }
      .navbar-nav li:hover > ul.dropdown-menu {
        display: block;
      }
      .dropdown-submenu {
        position: relative;
      }
      .dropdown-submenu > .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
      }

      /* rotate caret on hover */
      .dropdown-menu > li > a:hover:after {
        text-decoration: underline;
        transform: rotate(-90deg);
      }
      @media screen and (max-width: 540px) {
        .centerOnMobile {
          text-align: center;
        }
      }
    </style>
  </head>

  <body>
    <div class="superNav border-bottom py-2 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
            <select class="me-3 border-0 bg-light">
              <option value="en-us">EN-US</option>
            </select>
            <span
              class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"
              ><strong>info@somedomain.com</strong></span
            >
            <span class="me-3"
              ><i class="fa-solid fa-phone me-1 text-warning"></i>
              <strong>1-800-123-1234</strong></span
            >
          </div>
          <div
            class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-none d-lg-block d-md-block-d-sm-block d-xs-none text-end"
          >
            <span class="me-3"
              ><i class="fa-solid fa-truck text-muted me-1"></i
              ><a class="text-muted" href="#">Shipping</a></span
            >
            <span class="me-3"
              ><i class="fa-solid fa-file text-muted me-2"></i
              ><a class="text-muted" href="#">Policy</a></span
            >
          </div>
        </div>
      </div>
    </div>
    <nav
      class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm "
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'shop:products' %}"
          ><i class="fa-solid fa-shop me-2"></i>
          <strong>BigCorp SHOP</strong></a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
          <div class="input-group">
            <span class="border-success input-group-text bg-success text-white"
              ><i class="fa-solid fa-magnifying-glass"></i
            ></span>
            <input
              type="text"
              class="form-control border-success"
              style="color: #7a7a7a"
            />
            <button class="btn btn-success text-white">Search</button>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <div class="ms-auto d-none d-lg-block">
            <div class="input-group">
              <span
                class="border-success input-group-text bg-success text-white"
                ><i class="fa-solid fa-magnifying-glass"></i
              ></span>
              <input
                type="text"
                class="form-control border-success"
                style="color: #7a7a7a"
              />
              <button class="btn btn-success text-white">Search</button>
            </div>
          </div>
          <ul class="navbar-nav ms-auto">
            {% for i in categories %}
            
            {% if not i.children.all %}
              <li class="nav-item">
                <a class="nav-link" href="{{i.get_absolute_url}}">{{i.name|upper }}</a>
              </li>
            {% else %}
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="{{i.get_absolute_url}}"
                  id="navbarDropdownMenuLink"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                {{i.name|upper}}
              </a>
                <ul
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  {% for obj in i.children.all %} {% if not obj.children.all %}
                    <li><a class="dropdown-item" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a></li>
                  {% else %}
                    <li class="dropdown-submenu">
                      <a class="dropdown-item dropdown-toggle" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a>
                      
                      <ul class="dropdown-menu">
                    {% for subobj in obj.children.all %} {% if not subobj.children.all %}
                        <li>
                          <a class="dropdown-item" href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>
                        </li>
                    {% else %}
                    <li class="dropdown-submenu">
                      <a class="dropdown-item dropdown-toggle" href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>
                      
                      <ul class="dropdown-menu">
                        {% for lastobj in subobj.children.all %} 
                        <li>
                          <a class="dropdown-item" href="{{lastobj.get_absolute_url}}">{{lastobj.name|upper}}</a>
                        </li>
                       {% endfor %}
                      </ul>
                    </li>
                    {% endif %} {% endfor %}
                  </ul>
                </li>
                {% endif %} {% endfor %}
              </ul>
            </li>
            {% endif %} {% endfor %}
          </ul>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url 'cart:cart' %}"
                > <i class="fa fa-shopping-cart" aria-hidden="true"> </i> Cart
                <span id="lblCartCount" class="badge badge-warning ">

                  {% with cart_qty=cart|length%}
                    {% if cart_qty > 0 %}
                    {{cart_qty}}
                    {% else %}
                      0
                    {% endif %}

                  {% endwith %}
                </span>
                </a>
            </li>

             {% if user.is_authenticated %}

             <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url "account:dashboard" %}"
                ><i class="fa-solid fa-circle-user me-1"></i> Dashboardr</a>
            </li>

            <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url "account:logout" %}"
                ><i class="fa-solid fa-circle-user me-1"></i> Logout</a>
            </li>
             
             
             {% else %}
             
             <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url "account:register" %}"
                ><i class="fa-solid fa-circle-user me-1"></i> Register</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url "account:login" %}"
                ><i class="fa-solid fa-circle-user me-1"></i> Login</a
              >
            </li>
             
             {% endif %} 

            
          </ul> 
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </body>
</html>