base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls"), name="shop"),
    path("email/", include(email_urls)),
    path("account/", include("account.urls")),
    path("cart/", include("cart.urls"), name="cart"),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from django.shortcuts import render
from . import views
from django.contrib.auth.decorators import login_required


app_name = "payment"

urlpatterns = [
    path(
        "shipping/",
        login_required(views.ShippingAddressView.as_view()),
        name="shipping",
    ),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("complete-order/", views.order_complete, name="complete-order"),
    path(
        "payment-success/", views.PaymentSuccessView.as_view(), name="payment-success"
    ),
    path("payment-failed/", views.PaymentFailedView.as_view(), name="payment-failed"),
]

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product


class ShippingAddress(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    full_name = models.CharField(
        max_length=100,
    )
    city = models.CharField(
        max_length=150,
    )
    street = models.CharField(max_length=150)
    zip_code = models.IntegerField(blank=True, null=True)


class Order(models.Model):
    shipping_address = models.ForeignKey(ShippingAddress, on_delete=models.CASCADE)

    total_price = models.IntegerField()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    quantity = models.SmallIntegerField()

payment/forms.py
from typing import Any
from django import forms


from .models import ShippingAddress


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        exclude = ["user"]

payment/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from cart.cart import Cart
from django.urls import reverse_lazy, reverse
from .forms import ShippingAddressForm
from shop.models import Product
from .models import ShippingAddress, Order, OrderItem
from django.views.generic import View, TemplateView
from django.http import JsonResponse
import stripe
from django.conf import settings
from base.settings import STRIPE_SECRET_KEY, STRIPE_VERSION
from decimal import Decimal


stripe.api_version = STRIPE_VERSION
stripe.api_key = STRIPE_SECRET_KEY


class ShippingAddressView(View):
    def get(self, request):
        profile, create = ShippingAddress.objects.get_or_create(user=request.user)

        form = ShippingAddressForm(instance=profile)

        return render(request, "payment/shipping.html", {"form": form})

    def post(self, request):
        profile = ShippingAddress.objects.get(user=request.user)

        form = ShippingAddressForm(request.POST, instance=profile)

        if form.is_valid():
            initial = form.save(commit=False)
            initial.user = request.user
            initial.save()

            return redirect("account:dashboard")

        return HttpResponseRedirect(request.META["HTTP_REFERER"])


class CheckoutView(View):
    def get(self, request):
        cart = Cart(request)
        for item in cart:
            print(item)
        if request.user.is_authenticated:
            ship_add, _ = ShippingAddress.objects.get_or_create(user=self.request.user)
            context = {"shipping_address": ship_add}
            return render(request, "payment/checkout.html", context)
        return render(request, "payment/checkout.html")


def order_complete(request):
    if request.method == "POST":
        email = request.POST["email"]
        full_name = request.POST["full_name"]
        city = request.POST["city"]
        street = request.POST["street"]
        zip_code = request.POST["zip_code"]

        user = request.user

        ship_address, _ = ShippingAddress.objects.get_or_create(
            user=user,
            defaults={
                "email": email,
                "full_name": full_name,
                "city": city,
                "street": street,
                "zip_code": zip_code,
            },
        )

        cart = Cart(request)

        total_price = cart.get_total_price()

        order = Order.objects.create(
            shipping_address=ship_address, total_price=total_price
        )

        for item in cart:
            OrderItem.objects.create(
                order=order,
                product=item["product"],
                quantity=item["qty"],
                price=item["price"],
            )

            session = stripe.checkout.Session.create(
                mode="payment",
                success_url=request.build_absolute_uri(
                    reverse("payment:payment-success")
                ),
                cancel_url=request.build_absolute_uri(
                    reverse("payment:payment-failed")
                ),
                line_items=[
                    (
                        {
                            "price_data": {
                                "unit_amount": int(item["price"] * Decimal(100)),
                                "currency": "uah",
                                "product_data": {"name": item["product"]},
                            },
                            "quantity": item["qty"],
                        }
                    )
                ],
            )

        print("Before redirect")  # Добавьте эту строку

        return redirect(session.url)


class PaymentSuccessView(TemplateView):
    template_name = "payment/payment-success.html"


class PaymentFailedView(TemplateView):
    template_name = "payment/payment-failed.html"

templates/payment/checkout.html
{% include "base.html" %}


{% load static %}


{% block content %}

<style>
    
    body 
    {
        
        background-color: gray;
    
    }


</style>


    <body>

        <br>

        <div class="container bg-white shadow-md p-5" style="width:500px; border-radius:20px;">

            <form id="form" method='POST', action="{% url "payment:complete-order" %}">

                {% csrf_token %}

                <div>

                    <h3> <i class="fa fa-chevron-circle-right" aria-hidden="true"></i> &nbsp; Complete your order </h3>

                    <p> Please enter in the relevant information below. </p>
 


                    <hr>

                    <br>

                    <div class="form-field">
                    
                        <input class="form-control validate" id="full_name" type="text" name='full_name' placeholder="Full name*" autocomplete="off" value="{{shipping_address.full_name}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="email" type="email" name='email' placeholder="Email address*" autocomplete="off" value="{{shipping_address.email}}" required>

                    </div>

                    
                    <br>

                    
                    <div class="form-field">

                        <input class="form-control validate" id="city" type="text" placeholder="City*" name='city' autocomplete="off" value="{{shipping_address.street_address}}" required>

                    </div>


                    <br>


                    <div class="form-field">

                        <input class="form-control validate" id="street" name='street' type="text" placeholder="Street" autocomplete="off" value="{{shipping_address.apartment_address}}" required>

                    </div>


                    <br>


                   <div class="form-field">

                        <input class="form-control validate" id="zip_code" name='zip_code' type="text" placeholder="Zip Code*" autocomplete="off" value="{{shipping_address.city}}" required>

                    </div>


                    <br>


                <br>



               <button id="complete-order" type="submit" class="btn btn-primary navbar-btn text-white"> &nbsp; Complete order </button>
               

                <br>




            </form>


        </div>

        

        <br>


    </body>


    <!-- Ajax integration -->

    

    
{% comment %} <script>
    $(document).on('submit', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "payment:complete-order" %}',
            data: {
                full_name: $('#full_name').val(),
                email: $('#email').val(),
                city: $('#city').val(),
                street: $('#street').val(),
                zip_code: $('#zip_code').val(),

                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'payment'
            },
            success: function(response){
                window.location.replace('{% url "payment:payment-success" %}')
                
            }, 
            error: function(error){
                window.location.replace('{% url "payment:payment-failed" %}')
            }
        })

    })


</script> {% endcomment %}





{% endblock %}

templates/payment/payment-failed.html
payment not ok

templates/payment/payment-success.html
payment ok

templates/payment/shipping.html
{%  include "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container bg-white shadow-md p-5 form-layout">
    
    <h3>Shipping</h3>
    
    <br>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary w-100 btn-block p-2 btn-register">Update</button>
    </form>

    <br>

    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                
            </li>
        {% endfor %}
    </ul>
{% endif %}

    
</div>

<br>

{% endblock content %}